---
# Galaxy worker nodes

- name: Slurm
  hosts: galaxy_workers
  roles:
    - role: galaxyproject.cvmfs
      tags: cvmfs
    - role: galaxyproject.slurm
      tags: slurm
    - role: geerlingguy.docker
      tags: docker
  post_tasks:
    - name: Copy epilog script
      ansible.builtin.copy:
        src: files/slurm/epilog.sh
        dest: /etc/slurm/epilog.sh
        mode: "0755"
        owner: root
        group: root
    - name: Copy gxit-port script
      ansible.builtin.template:
        src: galaxy/gxit-port.sh.j2
        dest: /usr/local/bin/gxit-port.sh
        mode: "0755"
        owner: root
        group: root
