---
# Install/Manage Galaxy stack

- name: PostgreSQL
  hosts: galaxy_db_servers
  roles:
    - role: galaxyproject.postgresql
    - role: galaxyproject.postgresql_objects
      become: true
      become_user: postgres
  tags:
    - postgres

- name: Slurm
  hosts: all
  roles:
    - role: galaxyproject.slurm
  tags:
    - slurm

- name: DRMAA for Slurm
  hosts: galaxy_servers
  tasks:
    - name: Install slurm-drmaa
      package:
        name: "{{ slurm_drmaa_rpm_url }}"
        disable_gpg_check: true
  tags:
    - slurm

#- name: Galaxy Initial Setup
#  hosts: galaxyservers
#  pre_tasks:
#    - name: Create Galaxy directories
#      file:
#        path: "{{ item }}"
#        state: directory
#        mode: 02770
#      loop: "{{ galaxy_precreate_dirs }}"
#      become: true
#      become_user: "{{ galaxy_user.name }}"
#  roles:
#    - role: galaxyproject.miniconda
#      become: yes
#      become_user: "{{ galaxy_user.name }}"
#    - role: galaxyproject.tusd
#  tags:
#    - galaxy

- name: NGINX
  hosts: galaxy_servers
  roles:
    - role: galaxyproject.nginx
  #post_tasks:
#  #  - name: Set nginx runtime group
#  #    lineinfile:
#  #      line: 'user www-data {{ galaxy_instance_group }};'
#  #      regexp: '^user .*;$'
#  #      path: /etc/nginx/nginx.conf
#  #    notify:
#  #      - restart nginx
  tags:
    - nginx

#- name: Galaxy post-install root
#  hosts: galaxyservers
#  roles:
#    - role: galaxyproject.galaxy
#      galaxy_manage_clone: no
#      galaxy_manage_static_setup: no
#      galaxy_manage_mutable_setup: no
#      galaxy_manage_database: no
#      galaxy_fetch_dependencies: no
#      galaxy_manage_errordocs: no
#      galaxy_build_client: no
#      galaxy_manage_systemd: yes
#      galaxy_manage_gravity: no
#      galaxy_manage_cleanup: yes
#  tags: galaxy, galaxy_post
