---

roles:
  - name: galaxyproject.cvmfs
    version: 0.3.0
  - name: galaxyproject.cvmfsexec
    version: 1.1.2
  - name: galaxyproject.gxadmin
    version: 0.0.13
  - name: galaxyproject.miniconda
    version: 0.3.3
  - name: galaxyproject.nginx
    version: 1.0.0
  - name: galaxyproject.postfix
    version: 0.2.1
  - name: galaxyproject.postgresql
    version: 1.1.7
  - name: galaxyproject.postgresql_objects
    version: 1.2.0
  - name: galaxyproject.pulsar
    version: 1.0.11
  - name: galaxyproject.slurm
    version: 1.0.4
  - name: galaxyproject.rabbitmq
    version: 1.0.1
  - name: galaxyproject.tusd
    version: 0.0.1
  - name: geerlingguy.redis
    version: 1.8.0
  #- name: usegalaxy_eu.certbot
  #  version: 0.1.11

collections:
  - name: galaxyproject.general
    version: 1.3.4
  - name: galaxyproject.galaxy
    version: 1.0.1
