---
# TACC hosts

all:

  vars:
    ansible_become: true
    ansible_connection: local
  #  ansible_user: root

  hosts:
    # TEMP for dual duty until we put some nodes in production
    cfde-galaxy-dev.tacc.utexas.edu:
      slurm_roles: [controller, exec]

  children:

    # Provides dev-specific values for group vars
    meta_galaxy_dev:
      children:
        galaxy_dev_servers:

    # Provides prod-specific values for group vars
    meta_galaxy_prod:
      children:
        galaxy_prod_servers:

    # Deploys and configures telegraf
    #telegraf_agents:

    # Deploys PostgreSQL and gxadmin
    galaxy_db_servers:
      children:
        galaxy_dev_servers:
        galaxy_prod_servers:

    # Deploys redis
    galaxy_redis_servers:
      children:
        galaxy_servers:

    # Sets some default variables for nginx package/config
    web_servers:
      children:
        galaxy_servers:

    # Deploys and configures RabbitMQ
    rabbitmq_servers:
      hosts:
        #.tacc.utexas.edu:

    # Creates:
    # - local gxsrc user
    # - telegraf plugins for Galaxy servers
    # - install cvmfs_remount_sync and prefer TACC stratum 1
    galaxy_servers:
      children:
        galaxy_dev_servers:
        galaxy_prod_servers:

    # Deploys cleanup cron jobs, removes any ansible_cron_galaxy_{{ galaxy_instance_codename }} jobs from other
    # galaxy_servers
    galaxy_cleanup_servers:
      hosts:
        #.tacc.utexas.edu:

    galaxy_dev_servers:
      hosts:
        cfde-galaxy-dev.tacc.utexas.edu:

    galaxy_prod_servers:
      hosts:
        cfde-galaxy.tacc.utexas.edu:

    # Deploys CVMFS and configures as a client
    cvmfs_clients:
      children:
        galaxy_servers:

    # Deploys Slurm client and configuration
    slurm_clients:
      children:
        galaxy_servers:

    slurm_controllers:
      vars:
        slurm_roles: [controller]
      hosts:
        cfde-galaxy-dev.tacc.utexas.edu:

    slurm_exec_hosts:
      vars:
        slurm_roles: [exec]
      hosts:
        cfde-galaxy-dev.tacc.utexas.edu:

    slurm_dbd_servers:
      hosts:
        #.tacc.utexas.edu:

    # Configures as a cluster node
    galaxy_nodes:
      children:
        cyclone_nodes:

    # Galaxy hosts from the VM stack
    galaxy_vms:
      vars:
        ansible_user: gxadm
        ansible_become: true
        ansible_ssh_executable: ./.ssh-keyboard-interactive
      hosts:
        #.tacc.utexas.edu:

    # Galaxy nodes from the Cyclone cloud
    cyclone_nodes:
      vars:
        ansible_user: root
      hosts:
        #foo: {ansible_host: 10.0.0.1}
